### ISSUE TITLE
Doubt regarding  streaming in and out of data between ADTF and CARLA

### ISSUE THREAD

**Issue by werewolfdev** [MrMushroom/CarlaScenarioLoader#4]
Hi , first of all nice thesis report. Really informative. I am actually trying to exchange target ego data live from CARLA to an ADTF Filter and ego data from ADTF Filter as well as the start and stop signals to CARLA. Could you suggest if I should be using ROS in between for the implementation or any suggestions on this end will be really helpful.

**Comment by MrMushroom** [comment]
Hi,

thanks! I hoped it would help someone ;)

Just to be sure: ADTF = Automotive Data and Time-Triggered Framework?
Also: would you like to use the scenario loading capability of this repo, or do you just want to connect CARLA via ADTF?

If the latter is true, I'd suggest using one of the more recent Carla versions and directly using their API (Python interface, or also C++ interface) to connect. The CARLA documentation is quite good and the people over at their discord are really active! Also their developers.

HTH

**Comment by werewolfdev** [comment]
Hi, thanks for the reply. Yes the same ADTF. Actually i would like to stream in original ego vehicle coordinate data from the real world, transform it into CARLAs coordinate frame live and run scenario . Do you know if it is possible to edit the xosc file live during a simulation.
 And as output I would like to put out the non-ego vehicle data to bypass the real world sensors . So basically I would like to establish a live in and out streaming between ADTF and carla. Regarding the document on ssame, I still havent found anything. I have tried messagig them in discord as well actually. Iam using 0.9.11 version of CARLA and controlling rhe ego vehicle now using simple_vehicle_control in xosc. I will give a check on the c++ interface for sure . Thanks in advance.

**Comment by werewolfdev** [comment]
Hi Do you have insights on whether I should use the ROS bridge and then connect with ADTF at the other end

**Comment by MrMushroom** [comment]
Streaming in EgoVehicle data is doable. If you only stream in the pose, then it's straightforward. if you want to use the Carla physics model and Carla pilot, it gets tricky.

Streaming data out should also be straightforward, by connecting to the sensors. However, I'm not the into the most recent Carla versions and I don't know, if the can provide diff models ... could be that you would have to compare to the ground truth yourself ...

What exactly do you mean by editing the xosc file live?
Basically, the Scenario file is a screenplay, so it's designed to initialize your actors in the beginning and then to act out the scene. In general, your xosc can be dynamic and also be reloaded. If specific dynamic features are missing, they should be added to the scenario loader, instead of using some file reloading hacks. In my world, I do not see the need to edit the scenario itself during runtime. But - as always - there might be a reason for you why you would like to do that. Maybe you could elaborate on that? :D

Currently not ... in my recent work, I'm focusing on V2X communications and do not need Carla. My general approach is to use as less and as much ROS as needed. I try to avoid it, when I want to stay simple. But for rapid prototyping, when I/we need it, we are abusing the hell out of it, to get quick results, as we already have a lot of in-house nodes. So if you do not use ROS for your vehicle prototypes, don't use it for your simulation. It just introduces new problems. If your vehicle platform is already using ROS, it might be better to use the Carla rosbridge.

**Comment by werewolfdev** [comment]
I can elaborate a bit about my work . Iam doing Vehicle in the Loop Testing . Its a mix of real world testing and simulation based testing. I will be sitting inside the vehicle in a test track and I will start the scene, send the first ego position into CARLA. Then with a trasnformation matrix(which is also a big problem as of now) transform this position as start position for the ego vehicle in the xosc file. Then for evry equivalent ego position I have to generate probably way point s in CARLA . And for each frame , I would like to send out the target vehicle reative position to the real world ECU through ADTF filters , as faked sensor data and see how the vehicle responds in the test track. 

I just would to stream out target vehicle position actually. It is actually send every fram from server to client right. I have properly lohgged this data into a csv using metrics manager module but when it comes to streaming the data live into an ADTF filter I basically have no idea. Same applies to streaming in Ego Data as well actually.

The trasnformation is also a bit tricky. Iam using Town01 with geo origin 0,0,0 ,I receive the ENU coordinates from the real car and geodetic point as well at the start of the scene. Iam not asure on how to implement this as well. Any insights on the same would also be helpful

**Comment by MrMushroom** [comment]
Ah okay that sounds great!
So the vehicle behavior is real life, as well as the sensor behavior, but the traffic participants are simulated. Got it.

I would then just send the current vehicle position to the simulator (I guess you have high ~1cm accuracy?). Pro-Tipp: if you also send the speed and steering angle (best if also rotation speed) to the simulator, then the simulator takes care of smooth physics and your vehicle won't lag (this is also pointed out somewhere in my thesis. I don't think its in my paper).

Streaming out vehicle position to your global frame should be straightforward with the [Carla Transform](https://carla.readthedocs.io/en/latest/python_api/#carlatransform) in the Python Interface. However, I don't know the specific requirements of ADTF ... would be trial and error (ähem ... reading the docs of course :P) for me too.

For getting stuff into the simulator there is also a slight hack ... if you do not have steep inclines or much stress on the vehicle, you can calculate transformations and rotations in 2D. the simulator does the rest. for roll and pitch, as well as for height, just take the current value of the simulator. If you update often, and if physics is activated for the ego car, the simulator takes care of the rest ... It's messy, but it's suitable for first tests!

In general, transformations also give me a knot in my head ... but it does help to read some [theory](http://motion.cs.illinois.edu/RoboticSystems/CoordinateTransformations.html)

**Comment by werewolfdev** [comment]
Hi thanks a lot for the detailed reply . Regarding the theory I have used the same source actually. In real world we have coordinates in ENU(with ENU tangential plane origin at a particular geodetic lat,lon and alt) and in CARLA in ESU with ESU origin aligned with geodetic origin (0,0,0). So Iam thinking if a trnasformation is even possible.

Secondly Iam confused about how I can edit the xosc file other than manually. Now Iam running the world and then with scenario runner py script Iam loading the open scenario file . So perhaps I have to edit it through scenario runner then .

**Comment by werewolfdev** [comment]
Regarding updating the ego vehicle waypoints , I think we could make use of the controllers. For example running the scenario runner script in external control and running manual_control.py lets you run the ego vehicle with keyboard within the scenario. Still the initial position is defined under openSCENARIO .Have to find something regarding that as well

**Comment by werewolfdev** [comment]
Hey as I have seen in ur report u receive ego vehicle coordinates to CARLA from ROS. Could you please tell me how you did that conversions , since you are aware that we cannot spawn a car anyhwere in our CARLA maps. This will be really helpful since we are not currently getting a technique to transform between real world and CARLA map coordiantes.

**Comment by MrMushroom** [comment]
No worries, conversion is possible ;)
-> It's just frame conversion ... similar like if you convert the sensor data positions to the base frame of the vehicle.
-> ROS takes care of things like that in an easy way. but in fact its just a matrix conversion, if you do it by hand ... meaning for all three values there should be a one line formula with some subtraction and cos calculations. (Unfortunately don't know them by heart)

I am not aware of a xosc editor ... I used notepad++ (windows) and geany(ubuntu). That was one of the biggest critique points in my work, as I think the format will not take off, as long as the standard is not as much specified, so that a scenario creation tool can create such a scenario file.

I did that with set_location ([actor method](https://carla.readthedocs.io/en/latest/python_api/)). Also I did not have to do the conversions, as our algorithms worked just fine with the CARLA coordinate frame ... in fact the coordinate frame is just "off-center"

**Comment by werewolfdev** [comment]
I think I can use the xosc file to set the initial position and then use external_control to use yome python script like manual_control.py and instead of using keyboard control can collect the transformed coordinated data from ADTF via UDP and update the location using the suggested set_location function of class Actor . This is just an idea , have to see if it can be implemented in real time.

Regarding coordinate transformation, I receive Ego coordinates in ENU (East North Up) Tangential plane , whose origin is entangled to a particular geodetic coordinate (lat,lon,alt). And the CARLA frame gives location in ESU coordinate frame. And since i use town01 the x,y,z 0,0,0 coincides with geodetic 0,0,0. Iam aware of translation and rotation matrixes concepts but due to involvement of these local ENU , ESU frames Iam confused.

**Comment by MrMushroom** [comment]
If you got the performance in your machines, it should work :D
-> If your program gets more complex, just be aware of the python global interpreter lock (GIL). This fucked things up for me a little bit :/

Ah, now I know what you mean! Yes, I had to flip the axis for the ROS connection [here](https://github.com/MrMushroom/CarlaScenarioLoader/blob/master/support/present.py) at line 134

**Comment by werewolfdev** [comment]
Yes hopefully. Yes i will keep a check on the GIL . Thanks for that . Yes since you had to convert from the left handed Unreal coordinate frame to the right handed frame which is commonly used. Thanks for ur insights and time. Will see

**Comment by MrMushroom** [comment]
Good luck with your work ;)

**Comment by werewolfdev** [comment]
Hi @MrMushroom I have started trying to retrieve the ego position and adversary positive live from the world. Iam able to record the data and retrieve it using the metrics manager module available from the logged binary string . But my need is to stream out the ego and adversary position live frame by frame and Iam not successful until now. Do you have any insights on this . Earlier u mentioned about connecting to sensors but this ego and target vehicle position are not related to any sensors and just direclty provided by carla world to client if Iam not wrong. Kindly provide your insights on the same.
